# Generated by Django 5.0 on 2023-12-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
