# Generated by Django 5.0 on 2023-12-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
    ]
